# Key metadata about the site
site_name: "DCB0129 Clinical Safety Management File Template"
site_description: "A template for creating clinical safety management files"
site_author: "Turva"
site_url: "https://turva.org"

# Zensical processes files in this folder into a HTML site
docs_dir: clinical-safety-management-file

# Copyright information which is shown in the footer
copyright: "Copyright &copy; 2026 Turva & Koloki Ltd - CC-BY-SA"

# these lines configure the 'GitHub repo' widget on the top right
repo_url: "https://github.com/clinicians-who-code/clinical-safety-hazard-documentation"
repo_name: "clinical-safety-hazard-documentation"
edit_uri: blob/main/clinical-safety-management-file

# `zensical serve` serves the docs locally on this (arbitrarily chosen) port
dev_addr: "0.0.0.0:8001"

# Navigation structure
nav:
  - Home: "index.md"
  - "clinical-safety-management-system.md"
  - "clinical-safety-management-plan.md"
  - "clinical-safety-case-report.md"
  - "hazard-log.md"
  - "security.md"
  - "third-party-tools-safety-assmt.md"
  - "download.md"
  - "contact.md"
  - "license.md"

# theme settings, fonts, colours
theme:
  # variant: classic # Zensical's 'Material for MkDocs' look
  variant: modern # Zensical's default theme

  # replace these path or the contents of the files to change the logo and favicon
  logo: _assets/_images/turva-transparent.svg
  favicon: _assets/_images/favicon.png

  features:
    - navigation.instant
    # uncomment the below two lines for Tabbed navigation (along the header bar)
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
    - navigation.expand
    # - toc.integrate

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    code: Roboto Mono

# zensical plugins
plugins:
  - git-committers:
      repository: "**REPOSITORY_URL**"
      branch: main
      enabled: false # makes Git Committers optional
  - git-revision-date-localized:
      enable_creation_date: true
  - search
  - with-pdf:
      #cover: false
      #back_cover: true
      #cover_subtitle: SUBTITLE TEXT
      #custom_template_path: TEMPLATES PATH
      #
      #toc_title: TOC TITLE TEXT
      #heading_shift: false
      #toc_level: 3
      #ordered_chapter_level: 2
      #excludes_children:
      #    - 'release-notes/:upgrading'
      #    - 'release-notes/:changelog'
      #
      #exclude_pages:
      #    - 'bugs/'
      #    - 'appendix/contribute/'
      #convert_iframe:
      #    - src: IFRAME SRC
      #      img: POSTER IMAGE URL
      #      text: ALTERNATE TEXT
      #    - src: ...
      #two_columns_level: 3
      #
      #render_js: true
      #headless_chrome_path: headless-chromium
      #
      # output_path:
      # enabled_if_env:
      #
      #debug_html: true
      #show_anchors: true
      #verbose: true

# additional markdown features
markdown_extensions:
  - zensical.extensions.macros:
      include_yaml:
        - variables.yml
  - abbr
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:zensical.extensions.emoji.twemoji
      emoji_generator: !!python/name:zensical.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - toc:
      permalink: true

# Placeholder variables for {{ macros }} are defined in variables.yml
